/** All backend API endpoint strings — mirrors backend route definitions */
export const EP = {
  // Auth
  AUTH_REGISTER_REQUEST: '/api/auth/register/request',
  AUTH_REGISTER_MOBILE_SEND_OTP: '/api/auth/register/mobile/send-otp',
  AUTH_REGISTER_VERIFY_EMAIL: '/api/auth/register/verify-email',
  AUTH_REGISTER_VERIFY_MOBILE: '/api/auth/register/verify-mobile',
  AUTH_REGISTER_COMPLETE: '/api/auth/register/complete',
  AUTH_REGISTER_RESEND: '/api/auth/register/resend',
  AUTH_REGISTER_VERIFY: '/api/auth/register/verify',
  AUTH_REGISTER: '/api/auth/register',
  PUBLIC_SITE_CONFIG: '/api/public/site-config',
  APP_HOME_BANNERS: '/api/app/home-banners',
  AUTH_LOGIN: '/api/auth/login',
  AUTH_REFRESH: '/api/auth/refresh',
  AUTH_LOGOUT: '/api/auth/logout',
  AUTH_ME: '/api/auth/me',
  AUTH_SESSION: '/api/auth/session',
  AUTH_SESSIONS_REVOKE_ALL: '/api/auth/sessions/revoke-all',
  AUTH_FORGOT_PASSWORD: '/api/auth/forgot-password',
  AUTH_RESET_PASSWORD: '/api/auth/reset-password',
  AUTH_PROFILE: '/api/auth/profile',
  AUTH_PROFILE_PHONE_SEND_OTP: '/api/auth/profile/phone/send-otp',
  AUTH_PROFILE_AVATAR: '/api/auth/profile/avatar',
  AUTH_PASSWORD: '/api/auth/password',
  AUTH_2FA_STATUS: '/api/auth/2fa/status',
  AUTH_2FA_SETUP: '/api/auth/2fa/setup',
  AUTH_2FA_VERIFY: '/api/auth/2fa/verify',
  AUTH_2FA_DISABLE: '/api/auth/2fa/disable',

  // Market data
  TRADING_MARKETS: '/api/trading/markets',
  TRADING_FEE_CONFIG: '/api/trading/fee-config',
  PUBLIC_FEE_CONFIG: '/api/public/fee-config',
  PUBLIC_EXCHANGE_SETTINGS: '/api/public/exchange-settings',
  TRADING_TICKER: (symbol: string) => `/api/trading/ticker/${symbol}`,
  TRADING_KLINES: (symbol: string) => `/api/trading/klines/${symbol}`,
  TRADING_ORDERBOOK: (symbol: string) => `/api/trading/orderbook/${symbol}`,
  TRADING_TRADES: (symbol: string) => `/api/trading/trades/${symbol}`,
  // IBO-as-quote pairs
  IBO_MARKETS: '/api/trading/ibo-markets',
  IBO_CANDLES: '/api/ibo/candles',
  IBO_ORDERBOOK: '/api/ibo/orderbook',
  IBO_TRADES: '/api/ibo/trades',
  IBO_TICKER: '/api/ibo/ticker',

  // Token listings (public)
  LISTINGS_NETWORK_OPTIONS: '/api/listings/network-options',
  LISTINGS_SUBMIT: '/api/listings/submit',
  LISTINGS_LISTED: '/api/listings/listed',
  LISTINGS_PAIRS: '/api/listings/pairs',

  // Spot orders
  ORDERS: '/api/orders',
  ORDERS_HISTORY: '/api/orders/history',
  ORDERS_TRADES: '/api/orders/trades',
  ORDER_CANCEL: (orderId: string) => `/api/orders/${orderId}`,

  // Portfolio
  PORTFOLIO_POSITIONS: '/api/portfolio/positions',
  PORTFOLIO_CLOSE: '/api/portfolio/close_position',

  // Wallet
  WALLET_ASSETS: '/api/wallet/assets',
  WALLET_BALANCES: '/api/wallet/balances',
  WALLET_DEPOSIT_ADDRESSES: '/api/wallet/deposit-addresses',
  WALLET_SUPPORTED_NETWORKS: '/api/wallet/supported-networks',
  WALLET_DEPOSIT_CATALOG: '/api/wallet/deposit-catalog',
  WALLET_WITHDRAW_CONFIG: '/api/wallet/withdraw-config',
  WALLET_WITHDRAW: '/api/wallet/withdraw',
  WALLET_WITHDRAWALS: '/api/wallet/withdrawals',
  WALLET_TRANSACTIONS: '/api/wallet/transactions',
  WALLET_DEPOSIT_EVENTS: '/api/wallet/deposit-events',
  WALLET_SIGNUP_BONUS_PENDING: '/api/wallet/signup-bonus-pending',
  WALLET_CHAINS: '/api/wallet/chains',
  WALLET_SWAP_CONFIG: '/api/wallet/swap/config',
  WALLET_SWAP_QUOTE: '/api/wallet/swap/quote',
  WALLET_SWAP: '/api/wallet/swap',
  WALLET_VERIFY_DEPOSIT: '/api/wallet/verify-deposit',
  WALLET_DEPOSIT_MONITOR_STATUS: '/api/wallet/deposit-monitor/status',
  WALLET_DEPOSIT_MONITOR_START: '/api/wallet/deposit-monitor/start',
  WALLET_DEPOSIT_MONITOR_SCAN: '/api/wallet/deposit-monitor/scan',
  WALLET_DEPOSIT_MONITOR_STOP: '/api/wallet/deposit-monitor/stop',

  // KYC
  KYC_UPLOAD: '/api/kyc/upload',
  KYC_UPLOAD_SIDE: (side: string) => `/api/kyc/upload/${side}`,
  KYC_SUBMIT: '/api/kyc/submit',
  KYC_STATUS: '/api/kyc/status',
  KYC_MODE: '/api/kyc/mode',
  KYC_DIGILOCKER_INIT: '/api/kyc/digilocker/init',
  KYC_DIGILOCKER_COMPLETE: '/api/kyc/digilocker/complete',
  KYC_PAN_VERIFY: '/api/kyc/pan/verify',
  KYC_FACE_MATCH: '/api/kyc/face-match',

  // Futures — mirrors futuresApi.js in ibo-exchange
  FUTURES_SYMBOLS: '/api/futures/symbols',
  FUTURES_MARK_PRICE: '/api/futures/mark-price',
  FUTURES_ORDERBOOK: '/api/futures/orderbook',
  FUTURES_TRADES: '/api/futures/trades',
  FUTURES_FUNDING_RATE: '/api/futures/funding-rate',
  FUTURES_WALLET: '/api/futures/wallet',
  FUTURES_WALLET_TXNS: '/api/futures/wallet/txns',
  FUTURES_WALLET_TRANSFER: '/api/futures/wallet/transfer',
  FUTURES_SETTINGS: '/api/futures/settings',
  FUTURES_LEVERAGE: '/api/futures/leverage',
  FUTURES_MARGIN_MODE: '/api/futures/margin-mode',
  FUTURES_ORDERS: '/api/futures/orders',
  FUTURES_ORDERS_OPEN: '/api/futures/orders/open',
  FUTURES_ORDERS_HISTORY: '/api/futures/orders/history',
  FUTURES_ORDER_CANCEL: (orderId: string) => `/api/futures/orders/${orderId}`,
  FUTURES_TRADES_ME: '/api/futures/trades/me',
  FUTURES_POSITIONS: '/api/futures/positions',
  FUTURES_POSITIONS_CLOSE: '/api/futures/positions/close',
  FUTURES_POSITIONS_HISTORY: '/api/futures/positions/history',
  FUTURES_WALLET_SYNC_LOCKED: '/api/futures/wallet/sync-locked',

  // Options
  OPTIONS_UNDERLYINGS: '/api/options/underlyings',
  OPTIONS_CONTRACTS: '/api/options/contracts',
  OPTIONS_CHAIN: '/api/options/chain',
  OPTIONS_DEPTH: '/api/options/depth',
  OPTIONS_TRADES: '/api/options/trades',
  OPTIONS_WALLET: '/api/options/wallet',
  OPTIONS_ORDERS: '/api/options/orders',
  OPTIONS_ORDERS_OPEN: '/api/options/orders/open',
  OPTIONS_ORDERS_HISTORY: '/api/options/orders/history',
  OPTIONS_ORDER_CANCEL: (orderId: string) => `/api/options/orders/${orderId}`,
  OPTIONS_TRADES_ME: '/api/options/trades/me',
  OPTIONS_WALLET_TRANSFER: '/api/options/wallet/transfer',
  OPTIONS_POSITIONS: '/api/options/positions',
  OPTIONS_DEMO_CHAIN: '/api/options/demo-chain',
  OPTIONS_TICKER: (contractId: string) => `/api/options/ticker/${contractId}`,
  OPTIONS_ORDERBOOK: (contractId: string) => `/api/options/orderbook/${contractId}`,
  OPTIONS_TRADES_CONTRACT: (contractId: string) => `/api/options/trades/${contractId}`,
  OPTIONS_HISTORY: '/api/options/history',
  OPTIONS_PORTFOLIO: '/api/options/portfolio',
  OPTIONS_INDEX_PRICE: '/api/options/index-price',

  // INR fiat deposits
  INR_CONFIG: '/api/inr/config',
  INR_RATE: '/api/inr/rate',
  INR_PAYMENT_METHODS: '/api/inr/payment-methods',
  INR_DEPOSITS: '/api/inr/deposits',
  INR_DEPOSITS_GATEWAY: '/api/inr/deposits/gateway',
  INR_WITHDRAWALS: '/api/inr/withdrawals',
  INR_WITHDRAWALS_ELIGIBILITY: '/api/inr/withdrawals/eligibility',
  INR_WITHDRAWALS_PAYOUT_PROFILE: '/api/inr/withdrawals/payout-profile',

  // Referral
  REFERRAL_ME: '/api/referral/me',
  REFERRAL_TREE: '/api/referral/tree',

  // Support
  SUPPORT_TICKETS: '/api/support/tickets',
  SUPPORT_TICKET: (id: string) => `/api/support/tickets/${id}`,
  SUPPORT_TICKET_MESSAGES: (id: string) => `/api/support/tickets/${id}/messages`,
} as const;
