import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcPath = path.join(root, 'node_modules', 'jsqr', 'dist', 'jsQR.js');
const outPath = path.join(root, 'src', 'components', 'wallet', 'jsqrInline.ts');

const src = fs.readFileSync(srcPath, 'utf8');
const out = `/** Auto-generated by scripts/embed-jsqr.mjs — do not edit manually */\nexport const JSQR_INLINE_SCRIPT = ${JSON.stringify(src)};\n`;
fs.writeFileSync(outPath, out);
console.log('Wrote', outPath, `(${(out.length / 1024).toFixed(0)} KB)`);
